[package]
name = "cyclone"
version = "0.1.0"
edition = "2021"
rust-version = "1.64"
publish = false

[[bin]]
name = "cyclone"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
color-eyre = { version = "0.6.1" }
cyclone-server = { path = "../../lib/cyclone-server" }
telemetry-application = { path = "../../lib/telemetry-application-rs" }
tokio = { workspace = true }
tokio-vsock = { workspace = true }
